<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" total="4" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Failed suite [Default suite]" duration-ms="157" started-at="2016-05-19T22:26:00Z" finished-at="2016-05-19T22:26:00Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="110" started-at="2016-05-19T22:26:00Z" finished-at="2016-05-19T22:26:00Z">
      <class name="com.thalesgroup.services.cte.lis.dojo.RealGridsTest">
        <test-method status="PASS" signature="EmptyGrid()[pri:0, instance:com.thalesgroup.services.cte.lis.dojo.RealGridsTest@22a71081]" name="EmptyGrid" duration-ms="44" started-at="2016-05-20T00:26:00Z" finished-at="2016-05-20T00:26:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- EmptyGrid -->
        <test-method status="PASS" signature="RealGrid1()[pri:0, instance:com.thalesgroup.services.cte.lis.dojo.RealGridsTest@22a71081]" name="RealGrid1" duration-ms="40" started-at="2016-05-20T00:26:00Z" finished-at="2016-05-20T00:26:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- RealGrid1 -->
        <test-method status="FAIL" signature="RealGrid2()[pri:0, instance:com.thalesgroup.services.cte.lis.dojo.RealGridsTest@22a71081]" name="RealGrid2" duration-ms="11" started-at="2016-05-20T00:26:00Z" finished-at="2016-05-20T00:26:00Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Could not solve the grid ! 53 cells still remaining to sove.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Could not solve the grid ! 53 cells still remaining to sove.
	at org.testng.Assert.fail(Assert.java:94)
	at com.thalesgroup.services.cte.lis.dojo.SudokuTest$SolvedProblem.shallBeSolved(SudokuTest.java:64)
	at com.thalesgroup.services.cte.lis.dojo.RealGridsTest.RealGrid2(RealGridsTest.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- RealGrid2 -->
      </class> <!-- com.thalesgroup.services.cte.lis.dojo.RealGridsTest -->
    </test> <!-- Default test -->
    <test name="Default test(failed)" duration-ms="21" started-at="2016-05-19T22:26:00Z" finished-at="2016-05-19T22:26:00Z">
      <class name="com.thalesgroup.services.cte.lis.dojo.RealGridsTest">
        <test-method status="FAIL" signature="RealGrid2()[pri:0, instance:com.thalesgroup.services.cte.lis.dojo.RealGridsTest@591f989e]" name="RealGrid2" duration-ms="18" started-at="2016-05-20T00:26:00Z" finished-at="2016-05-20T00:26:00Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Could not solve the grid ! 53 cells still remaining to sove.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Could not solve the grid ! 53 cells still remaining to sove.
	at org.testng.Assert.fail(Assert.java:94)
	at com.thalesgroup.services.cte.lis.dojo.SudokuTest$SolvedProblem.shallBeSolved(SudokuTest.java:64)
	at com.thalesgroup.services.cte.lis.dojo.RealGridsTest.RealGrid2(RealGridsTest.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- RealGrid2 -->
      </class> <!-- com.thalesgroup.services.cte.lis.dojo.RealGridsTest -->
    </test> <!-- Default test(failed) -->
  </suite> <!-- Failed suite [Default suite] -->
</testng-results>
